apiVersion: v1
kind: Service
metadata:
  name: pod-metadata-service
  namespace: default  # 👈 Add this line
  labels:
    app: pod-metadata
spec:
  ports:
    - port: 80  # Changed to 80
      protocol: TCP
      targetPort: 80  # Changed to 80
  selector:
    app: pod-metadata
  type: NodePort
